version: '3.9'


services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - apps-nginx

networks:
  apps-nginx:
    external: true
