FROM python:3.11-slim-bookworm


USER root

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get autoremove && \
    apt-get autoclean && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .